Dm
AlexTomAQA/TestCapitalComPySe pull request #174
Opened 2024-01-03 16:18 UTC by Amid-Kirdum

2024-01-03 18:25 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          Language: All. License: All.
Уточнить доступность TC по странам и языкам.

2024-01-03 18:29 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
добавить проверку доступности по языкам и странам.

2024-01-03 18:37 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          page_conditions.preconditions(
комментарий для строки 56: проверку страны добавить перед методом preconditions
- добавить проверку языка перед методом preconditions
- реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:39 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          Check: Button [Try demo] on Main banner
скорректировать страны и языки.

2024-01-03 18:40 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          page_conditions.preconditions(
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:41 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          Check: Button [Trade] in Most traded block
скорректировать страны и языки.

2024-01-03 18:43 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          page_conditions.preconditions(
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:46 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +        Check: Button [1. Sell] in content block
скорректировать намиенование кнопки [Sell]

2024-01-03 18:48 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +            test_element.arrange_(cur_item_link, button='sell')
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:49 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +        Check: Button [1. Buy] in content block
скорректировать наиvенование кнопки [Buy]
скорректировать языки и лицензии

2024-01-03 18:50 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +            test_element = ButtonsSellBuyInContentBlock(d, cur_item_link)
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:51 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +        Check: Button [1. Get started] on Sticky bar
скорректировать наиvенование кнопки [Get started]
скорректировать языки и лицензии

2024-01-03 18:52 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +            test_element = GetStartedOnStickyBar(d, cur_item_link)
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:53 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +        Check: Button [Start trading] in content block
скорректировать языки и лицензии

2024-01-03 18:54 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          if cur_country != 'gb':
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:55 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +    @allure.step("Start test of button [Create your account] in block [Steps trading]")
скорректировать наименование блока Block "Still looking for a platform/broker you can trust?"

2024-01-03 18:56 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
>          Language: All. License: All.
скорректировать языки и лицензии

2024-01-03 18:57 UTC, artemdashkov commented on tests/US_11_Education/US_11-02-05_Cryptocurrency_trading/us_11-02-05-01_cryptocurrency_trading_test.py
> +            test_element = BlockStepTrading(d, cur_item_link)
проверку страны добавить перед методом preconditions

добавить проверку языка перед методом preconditions
реализован старый подход для тестирования элемента, где создается тестируемый элемент и вызывается полный тестируемый метод

2024-01-03 18:59 UTC, artemdashkov requested changes
внести изменения согласно комментариям по тексту.

2024-01-11 19:51 UTC, closed without merging

2024-01-11 19:55 UTC, AlexTomAQA commented
Я не могу принять одновременно 2 правильных и остальные не правильные ТК не принять.
Поэтому, исправляй все тк в соответствии с замечаниями Артема.
А закончишь, на это не должно уйти много времени, то сделаешь новый PR

2024-01-16 21:04 UTC, Amid-Kirdum commented
Ок, понял, буду исправлять и делать новый PR