Commits on Feb 14, 2024: modified and write test_01 for US_11-00-00
AlexTomAQA/TestCapitalComPySe pull request #377
Opened 2024-02-14 12:06 UTC by podchasova11

Commits on Feb 14, 2024

1. modified pages/Elements/ButtonOpenAnAccountMainBanner
2. rename CSS-selector BUTTON_OPEN_AN_ACCOUNT
3. modified and write test_01 for US_11-00-00

2024-02-14 13:09 UTC, MikeTaran requested changes
Хорошая работа, код логичный и читаемый. 
Замечания не существенные

2024-02-14 13:09 UTC, MikeTaran commented on pages/Elements/ButtonOpenAnAccountMainBanner.py
> +    def full_test(self, d, cur_language, cur_country, cur_role, cur_item_link):
Этот метод можно убрать, он не используется: def full_test

2024-02-14 13:09 UTC, MikeTaran commented on pages/Elements/ButtonOpenAnAccountMainBanner.py
> +        self.driver.execute_script(
здесь можно использовать готовый метод из BasePage: self.go_to_element(self, element)

2024-02-14 13:09 UTC, MikeTaran commented on tests/US_11_Education/US_11-00-00_Learn_to_trade/US_11-00-00_Learn_to_trade_test.py
> +        link = page_conditions.preconditions(
Для нового дизайна сайта данный метод preconditions, не корректно работает при Auth и NoAuth ролях - разлогинивает при смене лицензии, поэтому правильнее было бы это учесть при тестировании. Сейчас есть временное решение - можно его и использовать, либо написать свое:  
from tests.ReTestsManual.pages.conditions_new import NewConditions
page_conditions = Conditions(d, "")
        link = page_conditions.preconditions(
            d, CapitalComPageSrc.URL_NEW, "", cur_language, cur_country, cur_role, cur_login, cur_password)

2024-02-14 15:44 UTC, podchasova11 commented on tests/US_11_Education/US_11-00-00_Learn_to_trade/US_11-00-00_Learn_to_trade_test.py
> +        link = page_conditions.preconditions(
Изменила page_conditions = NewConditions(d, "")
добавила CapitalComPageSrc.URL_NEW
Импортировала from tests.ReTestsManual.pages.conditions_new import NewConditions

2024-02-14 16:52 UTC, MikeTaran approved these changes

2024-02-15 04:57 UTC, AlexTomAQA approved these changes

2024-02-15 04:57 UTC, merged